spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        default_batch_fetch_size: 1000
        use-new-id-generator-mappings: false
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

product-rds:
  datasource-write:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbc-url: jdbc:tc:postgresql:12.7:///product
    username: product
    password: product
  datasource-read:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbc-url: jdbc:tc:postgresql:12.7:///product
    username: product
    password: product